create table users
(
    id      varchar(255) not null
        constraint users_pkey
            primary key,
    email   varchar(255),
    gender  varchar(255),
    locale  varchar(255),
    name    varchar(255),
    userpic varchar(255)
);

create table notes
(
    id      bigint generated by default as identity
        constraint notes_pkey
            primary key,
    text    varchar(255),
    time    timestamp,
    title   varchar(255)
        constraint uk_notes_title
            unique,
    user_id varchar(255)
        constraint uk_notes_user_id
            references users
);


create table users_notes
(
    user_id  varchar(255) not null
        constraint fk_user_id
            references users,
    notes_id bigint       not null
        constraint uk_notes_id
            unique
        constraint fk_user_notes
            references notes
);

